using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Library_Management_System.Models
{
    public class Book
    {
        public int BookID { get; set; } //autogenerated
        public int ISBN { get; set; }
        public string BookTitle { get; set; }
        public string Author { get; set; }
        public string Availability { get; set; }
        public string Location { get; set; }

        public Book() { }
        public Book(int iSBN, string bookTitle, string author, string availability, string location)
        {
            //BookID
            ISBN = iSBN;
            BookTitle = bookTitle;
            Author = author;
            Availability = availability;
            Location = location;
        }

        public override string ToString()
        {
            return $"Book Details:\nBookID: {BookID}, ISBN: {ISBN}, Title: {BookTitle}, Author: {Author} Availability: {Availability}, Location: {Location}";
        }

    }
}
